// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Rms_Core_313.DataBaseContext.DataBaseContext;

namespace Rms_Core_313.DataBaseContext.Migrations
{
    [DbContext(typeof(ProjectDbContext))]
    [Migration("20200512142805_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Rms_Core_313.Model.Models.CreateType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("createTypes");
                });

            modelBuilder.Entity("Rms_Core_313.Model.Models.MenusCreate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<int>("CreateTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Discriptions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<byte[]>("files")
                        .HasColumnType("varbinary(max)");

                    b.HasKey("Id");

                    b.HasIndex("CreateTypeId");

                    b.ToTable("menusCreates");
                });

            modelBuilder.Entity("Rms_Core_313.Model.Models.OrderPlace", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("IsCashOnDelivery")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("OrderPlaces");
                });

            modelBuilder.Entity("Rms_Core_313.Model.Models.OrderPlaceDetails", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("MenusCreateId")
                        .HasColumnType("int");

                    b.Property<long?>("OrderPlaceId")
                        .HasColumnType("bigint");

                    b.Property<long>("PlaceOrderId")
                        .HasColumnType("bigint");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MenusCreateId");

                    b.HasIndex("OrderPlaceId");

                    b.ToTable("OrderPlaceDetails");
                });

            modelBuilder.Entity("Rms_Core_313.Model.Models.TableBookingCreate", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GuestAmount")
                        .HasColumnType("int");

                    b.Property<bool>("IsBokkingConfirm")
                        .HasColumnType("bit");

                    b.Property<bool>("IsMailConfirm")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("tableBookingCreates");
                });

            modelBuilder.Entity("Rms_Core_313.Model.Models.MenusCreate", b =>
                {
                    b.HasOne("Rms_Core_313.Model.Models.CreateType", "CreateType")
                        .WithMany()
                        .HasForeignKey("CreateTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Rms_Core_313.Model.Models.OrderPlaceDetails", b =>
                {
                    b.HasOne("Rms_Core_313.Model.Models.MenusCreate", "menusCreate")
                        .WithMany()
                        .HasForeignKey("MenusCreateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Rms_Core_313.Model.Models.OrderPlace", null)
                        .WithMany("OrderPlaceDetails")
                        .HasForeignKey("OrderPlaceId");
                });
#pragma warning restore 612, 618
        }
    }
}
